[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "mazegen-a-maze-ing"
version = "0.1.0"
description = "A maze generator, exporter, and terminal visualizer."
requires-python = ">=3.10"
dependencies = []

[tool.setuptools]
py-modules = [
	"a_maze_ing",
	"mazegen",
	"config_parser",
	"output_writer",
	"visualizer",
]

[tool.setuptools.packages.find]
include = ["maze_generator*"]

